### ISSUE TITLE
For Cud?

### ISSUE THREAD

**Issue by Alexey-T** [0x3024/BBEdit#3]
Hi. I like these contrast 3024 schemes.
Can we have same schemes for CudaText? Format is json, file .cuda-theme-syntax.

**Comment by idleberg** [comment]
You're welcome to contribute a [template](https://github.com/chriskempson/base16-builder/tree/master/templates) for [base16-builder](https://github.com/chriskempson/base16-builder/), the software used to generate these schemes

**Comment by Alexey-T** [comment]
Hm, I think too much work for template

**Comment by idleberg** [comment]
I think that's why many new editors have adopted the TextMate format for templates
